### PR TITLE
dashboard_examples

### PR DESCRIPTION
**Pull request by GeekSheikh**
Initial release for dashboards and query examples.

Initial Release Dashboards include dashboards from the following dim focuses

* Clusters
* Jobs
* Notebooks
* Workspace
* Population (P1)
* DBSQL (P1)

### CODE REVIEW

**Comment by anogues-danone** [comment]
/Dashboards_Dev/In Progress/Helpers is not there?

**Comment by anogues-danone** [comment]
@GeekSheikh @mohanbaabu1996 @AnushaSure Hello.

Is it possible to get /Dashboards_Dev/In Progress/Helpers this file. We are interested in give it a go, but it's impossible to test without this file.

We can help on the testing as well.

Thanks!

**Comment by mohanbaabu1996** [comment]
Hi @anogues-danone ,

We're working diligently on it but it's not yet ready for consumption. As soon as it is ready and merge the PR, it will be ready to use. Thanks!

**Comment by anogues-danone** [comment]
Thanks @mohanbaabu1996!

Let me know if i can help.
Albert

**Pull request closed without merging**
