### PR TITLE
Externalize components

### LINKED ISSUE #164: Expose PipelineTable Attributes
Nearly all of the Target (PipelineTable) attributes are hidden from public access. Enable these.

### LINKED ISSUE #165: Enable Public Access to Modules
Modules should be publicly accessible from a pipeline instance. Enable this.

Furthermore, the linkage between a module and it's output target is also very valuable, this should be explored and enabled if possible.

### PR DESCRIPTION
**Pull request by GeekSheikh**
closes #165 
closes #164

### CODE REVIEW

**Comment by GeekSheikh** [comment]
@alexott -- I branched off of PR #243 so as to keep the merge simpler later. Please Complete #243 first and then only the commits from `Issue_165` (last 2) are relevant for review in this PR.

**Comment by venkat7vs** [comment]
@GeekSheikh 

You mentioned in the Github Docs that the Cluster Requirements for Overwatch are
DBR 7.3+ tests completed on latest LTS version.

Does it works for DBR 6.4 version?

**Comment by alexott** [comment]
maybe you rebase this branch after you merge #423 into master? It would be much easier to review it

**Comment by GeekSheikh** [comment]
@alexott -- well, since I squash and merge to main, the rebase was off of pipeline_enhancements not main, so we should have merged this into Pipeline enhancements. Either way just gonna merge this one. It was a small PR that just made a few functions public.

**Pull request merged**
