### PR TITLE
389 parallelize cluster events

### LINKED ISSUE #389: parallelize clusterEvents Bronze Module
driver parellelization should be supported in new APICallV2.

### PR DESCRIPTION
**Pull request by Sriram-databricks**
Multithreaded api call support added

closes
 #389 parallelize clusterEvents Bronze Module

### CODE REVIEW

**Comment by GeekSheikh** [comment]
@Sriram-databricks -- please try to squash your dup commits like `rough commit to send the error` and group your commits into milestones as your developing -- especially on these larger PRs.

**Comment by Sriram-databricks** [comment]
@GeekSheikh : i have already tried that but because the branch has 2 parents(api modernisation and use new api) it's not able to squish the commits.

**Comment by GeekSheikh** [comment]
oh yeah, let's finish 381 and then rebase this off of 6.1.2 after that's merged to simplify and clean this up for review.

**Comment by Sriram-databricks** [comment]
not required

**Pull request closed without merging**
