### PR TITLE
Update Azure/AWS Instance Types

### PR DESCRIPTION
**Pull request by mohanbaabu1996**
Update Azure/AWS Instance Types
#852

### CODE REVIEW

**Review by GeekSheikh — CHANGES_REQUESTED** [review]
All Hourly_DBUs values should be double. please add .0 to all of the values. All values should go to at least 1 decimal.

There seem to be some AWS machine types in the Azure csv -- let's make sure these are present in the was file and remove them from the Azure file.

Did you use the supported machine types link to verify all supported types are present in GCP as well?

**Comment by GeekSheikh** [comment]
@mohanbaabu1996 -- this is based to main -- please change the base to 0720_release branch

**Comment by mohanbaabu1996** [comment]
Hi @GeekSheikh ,

I've reviewed East US 2, West US2 , Central US, North Europe and South Asia regions, mostly all the instance types are covered. `Standard_NC4as_T4_v3`  and `Standard_NC4as_T4_v3` are already present in the table. Other two `Lasv3` and `Lsv3` are updated in PR `852_InstanceDetails` because not sure of how to change the base branch to this `PR_853`. Let me know if you've any confusion.

**Comment by mohanbaabu1996** [comment]
created new PR #876, so closing this old PR

**Pull request closed without merging**
